version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "process-map-data"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-168rpg03k2a2q"
s3_prefix = "process-map-data"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
